### ISSUE TITLE
offer of cooperation

### ISSUE THREAD

**Issue by KlassnayaAfrodita** [hokamsingh/lessgo#9]
hi, I'm new and wanted to join lessgo and I want to offer you my help in development. I've made some commits that can improve your project. if you agree, write to me e.v.kazanjan@gmail.com

**Comment by hokamsingh** [comment]
Thank you for the kind support. I'll look into your comments and maybe
later on we can work on it together. Can you please share your socials so
we can connect.

Best regards
Hokam Singh

**Comment by KlassnayaAfrodita** [comment]
Telegram: @MyNameIsEKJ

**Comment by hokamsingh** [comment]
I have sent you a mail.
